# INSTRUCTION ARG1 ARG2 ....
FROM centos:7
LABEL auther=tejaspatil
RUN yum install httpd -y
COPY index.html /var/www/html/index.html
EXPOSE 80
CMD httpd -DEFOREGROUND
# CMD ["httpd", "-DEFORGROUND"]
# ENTRYPOINT httpd -DEFOREGROUND
# ENTRYPOINT ["httpd","-DEFOREGROUND"]