# INSTRUCTION ARG1 ARG2 ....
FROM centos:7
RUN yum install httpd -y
RUN mkdir -p  /usr/local/apache2/htdocs/student
COPY index.html /usr/local/apache2/htdocs/student/
EXPOSE 80
ENTRYPOINT ["httpd","-DFOREGROUND"]