# INSTRUCTION ARG1 ARG2 ....
FROM centos:7
RUN yum install httpd -y
RUN mkdir -p /var/www/html/backend
COPY index.html /var/www/html/backend/index.html
COPY index1.html /var/www/html/
EXPOSE 80
ENTRYPOINT ["httpd","-DFOREGROUND"]